/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'CB07152567' at '5/2/14 10:11 AM' with Gradle 1.12
 *
 * @author CB07152567, @date 5/2/14 10:11 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
